export const GET_LIST_HIGHWAY = 'GET_LIST_HIGHWAY';
export const GET_HIGHWAY_DETAIL = 'GET_HIGHWAY_DETAIL';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const ADD_INFO_FOR_FAVORITE = 'ADD_INFO_FOR_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';